### ISSUE TITLE
Feature: User can Register

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account that they can log in to/log out from.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139753140-540d822b-b3b0-4a5e-888d-9e435be89783.png)

![image](https://user-images.githubusercontent.com/87685216/139753160-c927abd7-8a25-4f33-9bfa-472227a0e588.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle 'POST' requests for new usernames and passwords.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a form to register.
- [x] Create a component to display the form.
- [x] Create fetch request to server.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
