### ISSUE TITLE
Feature: User can View Itinerary Locations on Google Maps

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view itinerary locations on Google maps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on the "View Map" button, it will take them to the map page. There, they will be able to all locations on their itinerary on one map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139769194-05aad461-9281-40a1-a9fa-5b6f8e17bc77.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a geometry field.

### ☁️ Server

- [x] Update 'GET' request in `server/index.js` to include geometry field from the Google Places API. 
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client

- [x] Create button to view map.
- [x] Create a component to render the Google maps.
- [x] Fetch request for the tripId.
- [x] Fetch request for the itineraries with the tripId.
- [x] Update component to display markers for locations.
- [x] Update component to display an info window when the marker is clicked.
- [x] Create button to go back to itineraries.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
