### ISSUE TITLE
Feature: User can View Trips

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view trips

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the "Start Planning" button will take them to their "My Trips" page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/140196690-9a4bda10-13c6-4c20-be71-2a5e5b9a2baf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle 'GET' requests for the 'trips' database.

### ⚡ Client

- [x] Switch view using hash routing after submitting set trip length form.
- [x] Map trips database to render trips list.
- [x] Add button to bring user back to the "Add a new trip" form.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
