### ISSUE TITLE
Feature: User can Set the Length of the Trip

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set the length of the trip.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The length of the trip can be set and add an icon to their trip.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/140196746-6dc407ab-3b7c-4da0-913c-d26dfd386f2f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create table

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests to add the destination, icon URL, start and end date 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a header with a navigation menu
- [x] Create a component to create a form
- [x] A button that will pop up a modal to select the icons
- [x] A destination input
- [x] A start date input
- [x] An end date input
- [x] A button to submit the input

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
