### ISSUE TITLE
Bug: Dates are Off by One

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#28]
#### Desired Behavior

The app should select the dates and display the dates selected.

#### Actual Behavior

The app displays the dates selected by one day off instead.

#### Steps to Reproduce

The bug triggers when the range of dates of the trip and when the date of an itinerary is selected and submitted.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Look into time zone difference.
- [x] Add time zone difference.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
