### ISSUE TITLE
Design Update: User can Sign In and Sign Out

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#33]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can sign in and sign out.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

User will be able to access a demo log in. 

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![image](https://user-images.githubusercontent.com/87685216/144689055-88bf0c2c-38d0-4523-93ef-eab377cad472.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a button for the demo sign in.
- [x] Create an event handler for the sign in.
- [x] Create a post request.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
