### ISSUE TITLE
Bug: Address includes code

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#37]
#### Desired Behavior

> ##### The app should ...

The app should display the address correctly.

#### Actual Behavior

> ##### The app does this instead ...

On certain itinarary, the app displays code along with the address.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

To trigger the bug, user must add certain places.
![image](https://user-images.githubusercontent.com/87685216/145871199-3658ebbc-746d-4c6a-bb45-f319d6fd7f37.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Update `parse-address.js` to remove code.
- **Clean Up**
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
