### ISSUE TITLE
Feature: User can Add Itineraries to a Day

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add itineraries to a day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click the "+" button to add itineraries and assign them to a day within the start and end date.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/140619871-25a18ca8-12f4-4b24-ae33-0018c92d0d71.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle 'POST' requests to the itinerary db.
- [x] Update `server/index.js` to handle 'GET' requests to the itinerary db.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add button to bring up "Add a Place" page.
- [x] Update hash routing when the button is clicked.
- [x] Create a component that displays the form.
- [x] Fetch search results from the Google API using the inputs of the form.
- [x] Fetch the itineraries for the tripId from database.
- [x] Update the `itinerary-list` component to render itineraries.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
