### ISSUE TITLE
Bug:  Setting range on itinerary dates.

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#43]
#### Desired Behavior

> ##### The app should ...

The app should show only allow dates within the set date range.

#### Actual Behavior

> ##### The app does this instead ...

The app allows any date instead

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

To trigger the bug, you can select any dates outside the date range

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Create a fetch request in `itinerary-page` to pull data for `tripId`
- [x] Pass data to children components
- [x] Set a min and max value on the input in the `edit-itinerary-form`
- [x] Set a min and max value on the input in the `add-itinerary-form`
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
