### ISSUE TITLE
Feature: User can Add Notes to Each Itinerary

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add notes to each itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the itinerary card is expanded, the user can click on the notes section and add notes regarding that itinerary there.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139761933-c5f9a434-3779-42e8-ba64-5d148729d456.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle 'PATCH' request to itinerary db for notes.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `itinerary-list` component to include an textarea for notes.
- [x] Update `itinerary-list` component to handle handleChange.
- [x] Update `itinerary-list` component to handle handleBlur.
- [x] Create fetch request to server.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
