### ISSUE TITLE
Feature: User can View Itinerary

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able to see all the days of their trip, as well as the itineraries planned for each one.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139762520-7eb0a4c1-85eb-42b1-9e6a-6adf215bc86c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update  `server/index.js` to handle 'GET' request from the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create itinerary page 
- [x] Create itinerary component with dates of trip listed out.
- [x] Update hash routing to include tripId.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
