### ISSUE TITLE
Feature: User can Edit Itinerary

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the kabob icon on the itinerary card and select edit. That will bring them to the edit page for that card where they can update the date, start or end time.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139768961-e719ebfb-62a3-488c-8cd0-5d5a8c479316.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a 'PATCH' request to the database.
- [x] Update `server/index.js` to handle a 'GET' request with the `itineraryId` to the database
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client

- [x] Make the vertical ellipses handle a click.
- [x] Update component to display modal when ellipses is clicked.
- [x] When `edit` is clicked, bring the user to the edit page.
- [x] Update the itinerary form to render a edit form.
- [x] Create a fetch request to the server.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
