### ISSUE TITLE
Feature: User can View Details of Itinerary

### ISSUE THREAD

**Issue by barbara-liao** [barbara-liao/wanderlist#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of itinerary.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on the card of the itinerary, the card containing the details will expand out. If they click again, the card will collapse. If they click on another card while the current card is expanded, the current card will collapse and other card will expand.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87685216/139765965-5b03dcf5-17ae-4de4-b975-f6d55905a9dc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update the `itinerary-list` component to list the details
- [x] Update the `itinerary-list` component to accordion out the details when clicked

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
